# -*- coding: utf-8 -*-
"""Healthcare part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UY9hYGwZlXSftwXkcjhzm3T8ivLYgDh-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/DV SKILL /healthcare_dataset.csv')

"""**Convert Dates**"""

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

"""**Calculate Hospital Stay**"""

df['Stay Days'] = (df['Discharge Date'] - df['Date of Admission']).dt.days

"""**Stacked Bar Chart**"""

pd.crosstab(
    df['Medical Condition'],
    df['Insurance Provider'],
    values=df['Billing Amount'],
    aggfunc='sum'
).fillna(0).plot(kind='bar', stacked=True)

plt.title('Billing by Condition and Insurance')
plt.show()

"""**Violin Plot**"""

sns.violinplot(data=df, x='Medical Condition', y='Billing Amount')
plt.title('Billing Amount by Medical Condition')
plt.xticks(rotation=45)
plt.show()

"""**Monthly Patient Admissions**"""

df['Month'] = df['Date of Admission'].dt.month

df.groupby('Month').size().plot(kind='line', marker='o')

plt.title('Monthly Patient Admissions')
plt.xlabel('Month')
plt.ylabel('Number of Admissions')
plt.show()

"""**Correlation Matrix**"""

corr = df[['Age', 'Stay Days', 'Billing Amount']].corr()

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""**Executive** **Summary**"""

print("EXECUTIVE SUMMARY")
print("1. Monitor high billing amounts.")
print("2. Plan staff based on patient admission trends.")
print("3. Study the relationship between age, stay days, and billing.")
print("4. Review insurance costs and hospital expenses.")